services:
  - type: web
    name: verb-tense-web-app
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
